name: hospital_appointment_management
description: A Healthcare Appointment Management System
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  uuid: ^3.0.7

dev_dependencies:
  test: ^1.24.0
